name: Linter Check

on:
  push:
    branches:
      - develop # Remplacez par le nom de votre branche principale

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19' # Remplacez par la version de Node.js que vous utilisez

    - name: Install dependencies
      run: npm install # Assurez-vous d'ajuster cela en fonction de votre gestionnaire de paquets (npm ou yarn)

    - name: Run Linter
      run:  ./script/pre-commit-script.sh  # Assurez-vous de mettre le chemin correct vers votre script pre-commit.sh
