name: run-script

on:
  pull_request:
  push:
    branches: [develop, main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
        run: bash scripts/script.sh